name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2

  - name: Install deps
    run: npm install

  - name: Run Testsuite
    continue-on-error: false
    run: |
      npx hardhat test